name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest'

    - name: Install dependencies
      run: |
        # 添加 Visual Studio 包源
        choco source add -n=visualstudio https://aka.ms/vs/17/release/channel
        
        # 安装 cmake
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        
        # 安装 Visual Studio 2019 构建工具，使用手动指定的源
        choco install visualstudio2019-buildtools --source=visualstudio

    - name: Build the project with MSBuild
      run: |
        cmake -G "Visual Studio 16 2019" .
        cmake --build . --config Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./Release/*.exe
